title: ZoKratesPlus
description: ZoKratesPlus is a publicly funded project for exploring new application contexts, nurturing the zero knowledge community, and advancing zero knowledge based technologies.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman